config/routes.rb
Deangergoric::Application.routes.draw do
  get "resume/page"
  get "home/index"

  root 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  def page
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/views/home/index.html.erb
<h1>Dean Gergoric</h1>
<p>Hi, My name is Dean. I’m trying to grow my experience and learn much more, so I’m looking to find a challenging internship position in Web Development, and be effective where my skills and passion for programming can be helpful. Focus on web application architecture using Ruby on Rails. Passion for startups and new technologies.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Deangergoric</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>

	<div class='nav'>
		<p class='p-nav'><%= link_to 'About', home_index_path %>  | <%= link_to 'Resume', resume_page_path %> | <%= link_to 'Github', "https://github.com/gergoric26" %></p> 
	</div>

<%= yield %>

	<div>
		<h4>
			<a href="mailto:gergoric_dean@yahoo.com">Contact Dean</a>
		</h4>
	</div>

</body>

</html>

app/views/resume/page.html.erb
<div calss='con'>
<h1>Dean Gergoric</h1>
<p>30-70 32nd Street Astoria, NY 11102</p>
<p>Phone: (347)636-5621 |  E-Mail: gergoric_dean@yahoo.com </p>

<h2>Objective</h2>
<p>To find a challenging position in Web Development and be effective where my skills and passion for programming can be delivering results. Focus on web application architecture using Ruby on Rails. Passion for startups and new technologies.</p>

<h3>EDUCATION AND TRAINING</h3>
<h4>NYU School Of Professional Studies, NYC, USA<span class="tab"></span>2014</h4>
<ul>
	<li>Certificate in Ruby on Rails</li>
</ul>

<h4>New York Real Esatate Institute, NYC, USA<span class="tab1"></span>2011</h4>
<ul>
	<li>Real Estate Agent</li>
</ul>

<h4>Polytechinc Of Rijeka, Rijeka, Croatia<span class="tab2"></span>2006 - 2011</h4>
<ul>
	<li>BA in Traffic Engineering</li>
</ul>

<h4>High School Mate Blazine, Labin, Croatia<span class="tab3"></span>2002 - 2006</h4>
<ul>
	<li>Electrotechnic Engineering</li>
</ul>

<h3>EXPERIENCE</h3>

<h4>Gina La Fornarina Restaurant, Manager, Administrative Assistant</h4> <h4>05/2011–Present</h4>
<ul>
	<li>Provide customer service in high paced atmosphere.</li>
	<li>Manage and provide guidance for employees.</li>
	<li>Responsible for opening and closing the restaurant.</li>
	<li>Maintain and restock inventory.</li>
	<li>Administrative responsibilities include processing tip information for payroll and closing register.</li>
</ul>

<h4>Freelance Web Developer</h4> <h4>2012-2013</h4>
<ul>
	<li>Updating Existing Business Website.</li>
	<li>Building and Maintaining Website.  (Wordpress)</li>
	<li>Computer Troubleshooting.</li>
</ul>

<h4>Charles Rutenberg Realty, Real Estate Agent</h4> <h4>07/2012-05/2013</h4>
<ul>
	<li>Coordinate appointments to show homes to prospective buyers.</li>
	<li>Contact property owners and advertise services to solicit property sales listings.</li>
	<li>Interview clients to determine what type of property they are seeking.</li>
	<li>Advise clients on market conditions, prices, mortgages, legal requirements and related matters.</li>
</ul>

<h3>SKILLS</h3>
<ul>
	<li>Proficient in HTML, CSS</li>
	<li>Proficient in Ruby, Ruby on Rails</li>
	<li>Proficient in WordPress</li>
	<li>Proficient in Dreamweaver, Photoshop, Fireworks and Illustrator</li>
	<li>Proficient in SEO, keyword research, link building</li>
	<li>Familiar with JaveScript, MySQl, SQlite</li>
	<li>OSX and Windows</li>
	<li>Github</li>
</ul>

</div>